[versions]
androidx-navigation = "2.9.0"
androidx-room = "2.7.1"
androidx-test = "1.6.1"
androidx-test-espresso = "3.6.1"
com-google-dagger = "2.56.2"
com-squareup-okhttp3 = "4.12.0"
io-mockk = "1.14.2"
hiltCompiler = "1.3.0-alpha01"
org-jetbrains-kotlin = "2.1.21"
activityCompose = "1.10.1"
composeBom = "2025.05.01"
com-google-devtools-ksp = "2.1.21-2.0.1"
foundationAndroid = "1.8.2"
material3Android = "1.3.2"
uiToolingPreviewAndroid = "1.8.2"
runtimeLivedata = "1.8.2"
agp = "8.10.0"
junit = "1.2.1"
navigationDynamicFeaturesRuntime = "2.9.0"
junit5 = "5.10.1"
androidJunit5 = "1.10.0.0"
spotless = "6.25.0"
detekt = "1.23.6"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.7.0"
coreTesting = "androidx.arch.core:core-testing:2.2.0"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
coreKtx = "androidx.core:core-ktx:1.16.0"
androidx-annotation = "androidx.annotation:annotation:1.7.0"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
javax-inject = "javax.inject:javax.inject:1"
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
fragmentTesting = "androidx.fragment:fragment-testing:1.8.7"
navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
navigationSafeArgsPlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
navigationTesting = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
navigationUi = { module = "androidx.navigation:navigation-ui", version.ref = "androidx-navigation" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
navigationDynamicFeaturesFragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidx-navigation" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
roomGradlePlugin = { module = "androidx.room:room-gradle-plugin", version.ref = "androidx-room" }
testCoreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
espressoContrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
espressoIdlingResource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }
junitKtx = "androidx.test.ext:junit-ktx:1.2.1"
testRules = { module = "androidx.test:rules", version.ref = "androidx-test" }
testRunner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidToolsBuildGradle = "com.android.tools.build:gradle:8.13.1"
coil3 = "io.coil-kt.coil3:coil-compose:3.0.4"
coil3-view = "io.coil-kt.coil3:coil:3.0.4"
coil3-network = "io.coil-kt.coil3:coil-network-okhttp:3.0.4"
material = "com.google.android.material:material:1.12.0"
androidPlayCore = "com.google.android.play:feature-delivery:2.1.0"
androidPlayCoreKtx = "com.google.android.play:feature-delivery-ktx:2.1.0"
hiltAndroidGradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger" }
hiltAndroidTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "com-google-dagger" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "com-google-dagger" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
okhttp3LoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
okhttp3Mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "com-squareup-okhttp3" }
retrofit2ConverterGson = "com.squareup.retrofit2:converter-gson:3.0.0"
mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
mockkAndroid = { module = "io.mockk:mockk-android", version.ref = "io-mockk" }
striktCore = "io.strikt:strikt-core:0.35.1"
composeCompilerGradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
junit = "junit:junit:4.13.2"
kluentAndroid = "org.amshove.kluent:kluent-android:1.73"
kspGradlePlugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "com-google-devtools-ksp" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "org-jetbrains-kotlin" }
coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3"
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
androidx-navigation-dynamic-features-runtime = { group = "androidx.navigation", name = "navigation-dynamic-features-runtime", version.ref = "navigationDynamicFeaturesRuntime" }
turbine = "app.cash.turbine:turbine:1.2.1"
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
android-junit5-plugin = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "androidJunit5" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

    
[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "org-jetbrains-kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "com-google-dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
