[versions]
androidx-navigation = "2.9.0"
androidx-room = "2.4.1"
androidx-test = "1.4.0"
androidx-test-espresso = "3.3.0"
com-google-dagger = "2.56.2"
com-squareup-okhttp3 = "4.9.3"
io-mockk = "1.12.1"
org-jetbrains-kotlin = "2.1.20"
androidToolsBuildGradle = "8.10.0"
benManesPlugin = "0.52.0"
littlerobotsPlugin = "1.0.0"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.3.1"
coreTesting = "androidx.arch.core:core-testing:2.1.0"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.2"
coreKtx = "androidx.core:core-ktx:1.3.2"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:7.0.3"
fragmentTesting = "androidx.fragment:fragment-testing:1.3.2"
lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:2.2.0"
navigationDynamicFeaturesFragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidx-navigation" }
navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
navigationSafeArgsPlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
# navigationTesting has a new version, but it's not in the scope of this subtask to update all libraries.
# I will only update the plugins that were explicitly requested.
navigationTesting = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
navigationUi = { module = "androidx.navigation:navigation-ui", version.ref = "androidx-navigation" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
testCoreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
espressoContrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
espressoIdlingResource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }
junitKtx = "androidx.test.ext:junit-ktx:1.1.3"
testRules = { module = "androidx.test:rules", version.ref = "androidx-test" }
testRunner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidToolsBuildGradle = { module = "com.android.tools.build:gradle", version.ref = "androidToolsBuildGradle" }
com-android-tools-lint-lint-gradle = "com.android.tools.lint:lint-gradle:30.0.3"
benManesPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "benManesPlugin" }
glide = "com.github.bumptech.glide:glide:4.12.0"
material = "com.google.android.material:material:1.4.0"
androidPlayCore = "com.google.android.play:core:1.10.0"
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger" }
hiltAndroidGradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger" }
hiltAndroidTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger" } # Also has version 2.56.2
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "com-google-dagger" }
okhttp3LoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
okhttp3Mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "com-squareup-okhttp3" }
retrofit2ConverterGson = "com.squareup.retrofit2:converter-gson:2.9.0"
mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
mockkAndroid = { module = "io.mockk:mockk-android", version.ref = "io-mockk" }
striktCore = "io.strikt:strikt-core:0.33.0"
junit = "junit:junit:4.13.2"
littlerobotsPlugin = { module = "nl.littlerobots.version-catalog-update:nl.littlerobots.version-catalog-update.gradle.plugin", version.ref = "littlerobotsPlugin" }
kluentAndroid = "org.amshove.kluent:kluent-android:1.68"
org-jacoco-org-jacoco-agent = "org.jacoco:org.jacoco.agent:0.8.3"
org-jacoco-org-jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.7"
org-jetbrains-kotlin-kotlin-annotation-processing-gradle = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-gradle", version.ref = "org-jetbrains-kotlin" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-parcelize-compiler = { module = "org.jetbrains.kotlin:kotlin-parcelize-compiler", version.ref = "org-jetbrains-kotlin" } # kotlin-parcelize-compiler is part of kotlin
org-jetbrains-kotlin-kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "org-jetbrains-kotlin" } # kotlin-parcelize-runtime is part of kotlin
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "org-jetbrains-kotlin" }
coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2"

[plugins]
android = { id = "com.android.application", version.ref = "androidToolsBuildGradle" }
android-library = { id = "com.android.library", version.ref = "androidToolsBuildGradle" }
# android-reporting is not a plugin defined in the versions block, so I will not update it.
android-reporting = "android-reporting:7.0.3"
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidx-navigation" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
com-android-application = { id = "com.android.application", version.ref = "androidToolsBuildGradle" }
# com-android-asset-pack not in task, skip
com-android-asset-pack = "com.android.asset-pack:7.0.3"
com-android-asset-pack-bundle = "com.android.asset-pack-bundle:7.0.3"
com-android-base = "com.android.base:7.0.3"
com-android-dynamic-feature = "com.android.dynamic-feature:7.0.3"
com-android-internal-application = "com.android.internal.application:7.0.3"
com-android-internal-asset-pack = "com.android.internal.asset-pack:7.0.3"
com-android-internal-asset-pack-bundle = "com.android.internal.asset-pack-bundle:7.0.3"
com-android-internal-dynamic-feature = "com.android.internal.dynamic-feature:7.0.3"
com-android-internal-library = "com.android.internal.library:7.0.3"
com-android-internal-reporting = "com.android.internal.reporting:7.0.3"
com-android-internal-test = "com.android.internal.test:7.0.3"
com-android-internal-version-check = "com.android.internal.version-check:7.0.3"
com-android-library = { id = "com.android.library", version.ref = "androidToolsBuildGradle" }
com-android-lint = "com.android.lint:7.0.3"
com-android-reporting = "com.android.reporting:7.0.3"
com-android-test = "com.android.test:7.0.3"
benManesVersions = { id = "com.github.ben-manes.versions", version.ref = "benManesPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "com-google-dagger" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
kotlin-android-extensions = "kotlin-android-extensions:1.6.0" # This plugin is deprecated and removed in Kotlin 1.8.0. Keep as is.
kotlin-dce-js = "kotlin-dce-js:1.6.0"
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "org-jetbrains-kotlin" }
kotlin-native-cocoapods = "kotlin-native-cocoapods:1.6.0"
kotlin-native-performance = "kotlin-native-performance:1.6.0"
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-android = "kotlin-platform-android:1.6.0"
kotlin-platform-common = "kotlin-platform-common:1.6.0"
kotlin-platform-js = "kotlin-platform-js:1.6.0"
kotlin-platform-jvm = "kotlin-platform-jvm:1.6.0"
kotlin-scripting = "kotlin-scripting:1.6.0"
kotlin2js = "kotlin2js:1.6.0"
littlerobotsVersionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "littlerobotsPlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-android-extensions = "org.jetbrains.kotlin.android.extensions:1.6.0" # Deprecated
org-jetbrains-kotlin-js = "org.jetbrains.kotlin.js:1.6.0"
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-multiplatform-pm20 = "org.jetbrains.kotlin.multiplatform.pm20:1.6.0"
org-jetbrains-kotlin-native-cocoapods = "org.jetbrains.kotlin.native.cocoapods:1.6.0"
org-jetbrains-kotlin-native-performance = "org.jetbrains.kotlin.native.performance:1.6.0"
org-jetbrains-kotlin-platform-android = "org.jetbrains.kotlin.platform.android:1.6.0"
org-jetbrains-kotlin-platform-common = "org.jetbrains.kotlin.platform.common:1.6.0"
org-jetbrains-kotlin-platform-js = "org.jetbrains.kotlin.platform.js:1.6.0"
org-jetbrains-kotlin-platform-jvm = "org.jetbrains.kotlin.platform.jvm:1.6.0"
org-jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-scripting = "org.jetbrains.kotlin.plugin.scripting:1.6.0"
sonarqube = "org.sonarqube:3.3" # Not in task, skip
